<?php

namespace Shaqi\LlmsOptimizer\Services;

use Exception;
use Illuminate\Support\Str;
use Botble\Theme\Facades\Theme;
use Botble\Base\Facades\BaseHelper;
use Botble\Slug\Facades\SlugHelper;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Cache;

class LlmsGeneratorService
{
    protected array $contentTypes = [];

    public function generate(): string
    {
        $cacheKey = llms_optimizer_config('cache_key');
        $cacheDuration = (int) get_llms_optimizer_setting('cache_duration', llms_optimizer_config('defaults.cache_duration', 60));

        if ($cacheDuration > 0 && Cache::has($cacheKey)) {
            return Cache::get($cacheKey);
        }

        $content = $this->buildContent();

        if ($cacheDuration > 0) {
            Cache::put($cacheKey, $content, now()->addMinutes($cacheDuration));
        }

        return $content;
    }

    protected function buildContent(): string
    {
        $lines = [];

        // Always include plugin header
        $lines[] = 'Generated by Shaqi LLM Optimizer v1.0';
        $lines[] = '';

        if (get_llms_optimizer_setting('include_sitemap_reference', llms_optimizer_config('defaults.include_sitemap_reference', true))) {
            $sitemapUrl = $this->getSitemapUrl();
            if ($sitemapUrl) {
                $lines[] = '> The XML sitemap of this website can be found here: [sitemap.xml](' . $sitemapUrl . ')';
                $lines[] = '';
            }
        }

        $siteTitle = Theme::getSiteTitle() ?: setting('admin_title', config('app.name'));
        $lines[] = '# ' . $siteTitle;
        $lines[] = '';

        // Add custom site description if provided
        $siteDescription = get_llms_optimizer_setting('site_description', '');
        if ($siteDescription) {
            $lines[] = '> ' . $siteDescription;
            $lines[] = '';
        } elseif (get_llms_optimizer_setting('include_site_tagline', llms_optimizer_config('defaults.include_site_tagline', true))) {
            // Fallback to tagline if no custom description
            $tagline = theme_option('site_description') ?: setting('admin_description', '');
            if ($tagline) {
                $lines[] = '> ' . $tagline;
                $lines[] = '';
            }
        }

        $contentTypes = $this->getContentTypes();

        foreach ($contentTypes as $type => $data) {
            $section = $this->formatSection($type, $data);
            if ($section) {
                $lines[] = $section;
                $lines[] = '';
            }
        }

        // Add Optional section if enabled
        if (get_llms_optimizer_setting('include_optional_section', llms_optimizer_config('defaults.include_optional_section', false))) {
            $optionalSection = $this->buildOptionalSection();
            if ($optionalSection) {
                $lines[] = $optionalSection;
                $lines[] = '';
            }
        }

        $content = implode("\n", $lines);

        if (get_llms_optimizer_setting('include_token_count', llms_optimizer_config('defaults.include_token_count', false))) {
            $tokenCount = $this->estimateTokenCount($content);
            $content .= "\n---\nEstimated tokens: ~{$tokenCount}";
        }

        return apply_filters('llms_optimizer_output', $content);
    }

    public function getContentTypes(): array
    {
        $types = [];
        $maxItems = (int) get_llms_optimizer_setting('max_items_per_type', llms_optimizer_config('defaults.max_items_per_type', 100));
        $sortOrder = get_llms_optimizer_setting('sorting_order', llms_optimizer_config('defaults.sorting_order', 'newest'));

        // Get all slugable models dynamically
        $supportedModels = SlugHelper::supportedModels();

        foreach ($supportedModels as $modelClass => $modelName) {
            $settingKey = llms_optimizer_model_setting_key($modelClass, $supportedModels);
            $legacySettingKey = llms_optimizer_legacy_model_setting_key($modelClass);

            // Check if this content type is enabled in settings
            if (! get_llms_optimizer_setting(
                $settingKey,
                get_llms_optimizer_setting($legacySettingKey, true)
            )) {
                continue;
            }

            // Get items for this model
            $items = $this->getItemsForModel($modelClass, $maxItems, $sortOrder);

            if (!empty($items)) {
                // Use a clean section name
                $sectionName = $this->getSectionNameFromModel($modelClass, $modelName);
                $types[$sectionName] = $items;
            }
        }

        return apply_filters('llms_optimizer_content_types', $types);
    }

    /**
     * Generate clean section name from model
     * Example: Botble\Page\Models\Page => Pages
     */
    protected function getSectionNameFromModel(string $modelClass, $modelName): string
    {
        // If modelName is a closure, call it
        if (is_callable($modelName)) {
            return $modelName();
        }

        // Otherwise use the model name as-is or extract from class
        return $modelName ?: Str::plural(class_basename($modelClass));
    }

    /**
     * Get items for any slugable model dynamically
     */
    protected function getItemsForModel(string $modelClass, int $limit, string $sortOrder): array
    {
        try {
            // Get the model instance
            $model = app($modelClass);

            // Build query
            $query = $model->query();

            // Add published filter if model has status
            if (method_exists($model, 'scopeWherePublished')) {
                $query->wherePublished();
            }

            // Add slugable relationship
            $query->with('slugable');

            // Apply sorting
            if ($sortOrder === 'alphabetical') {
                $query->orderBy('name');
            } else {
                $query->orderByDesc('created_at');
            }

            // Get items
            $items = $query->limit($limit)->get();

            // Map to array format
            return $items->map(function ($item) {
                $data = [
                    'title' => $item->name ?? $item->title ?? 'Untitled',
                    'url' => $item->url ?? url($item->slug ?? ''),
                ];

                // Add description if available
                $description = $item->description ?? $item->excerpt ?? $item->content ?? null;
                if ($description) {
                    // Clean and truncate description
                    $description = strip_tags($description);
                    $description = str_replace(["\r", "\n", "\t"], ' ', $description);
                    $description = preg_replace('/\s+/', ' ', $description);
                    $description = trim($description);

                    if (strlen($description) > 150) {
                        $description = substr($description, 0, 147) . '...';
                    }

                    if ($description) {
                        $data['description'] = $description;
                    }
                }

                return $data;
            })->toArray();

        } catch (Exception $e) {
            // If any error occurs, return empty array
            return [];
        }
    }



    public function formatSection(string $type, array $items): string
    {
        if (empty($items)) {
            return '';
        }

        $items = apply_filters('llms_optimizer_items', $items, $type);

        if (empty($items)) {
            return '';
        }

        $title = ucfirst($type);
        $lines = ["## {$title}"];

        $linkFormat = get_llms_optimizer_setting('link_format', llms_optimizer_config('defaults.link_format', 'markdown'));
        $includeDescriptions = get_llms_optimizer_setting('include_descriptions', llms_optimizer_config('defaults.include_descriptions', true));

        foreach ($items as $item) {
            if ($linkFormat === 'markdown') {
                $line = "- [{$item['title']}]({$item['url']})";

                // Add description if available and enabled
                if ($includeDescriptions && !empty($item['description'])) {
                    $line .= ': ' . $item['description'];
                }

                $lines[] = $line;
            } else {
                $lines[] = "- {$item['title']}: {$item['url']}";
            }
        }

        return implode("\n", $lines);
    }

    protected function buildOptionalSection(): string
    {
        $lines = ['## Optional'];
        $hasContent = false;

        // Add custom optional links from settings
        $optionalLinks = get_llms_optimizer_setting('optional_links', '');
        if ($optionalLinks) {
            $linkLines = array_filter(array_map('trim', explode("\n", $optionalLinks)));
            foreach ($linkLines as $link) {
                if ($link) {
                    $lines[] = '- ' . $link;
                    $hasContent = true;
                }
            }
        }

        // Add sitemap if not already in header
        if (!get_llms_optimizer_setting('include_sitemap_reference', llms_optimizer_config('defaults.include_sitemap_reference', true))) {
            $sitemapUrl = $this->getSitemapUrl();
            if ($sitemapUrl) {
                $lines[] = '- [XML Sitemap](' . $sitemapUrl . ')';
                $hasContent = true;
            }
        }

        // Allow plugins to add optional content
        $lines = apply_filters('llms_optimizer_optional_section', $lines);

        // Check if any content was added beyond the header
        if (!$hasContent && count($lines) <= 1) {
            return '';
        }

        return implode("\n", $lines);
    }

    public function estimateTokenCount(string $content): int
    {
        $words = str_word_count($content);
        return (int) ceil($words / 0.75);
    }

    public function saveStaticFile(): bool
    {
        $content = $this->generate();
        $publicPath = public_path('llms.txt');

        try {
            File::put($publicPath, $content);
            return true;
        } catch (Exception $e) {
            BaseHelper::logError($e);
            return false;
        }
    }

    public function clearCache(): void
    {
        Cache::forget(llms_optimizer_config('cache_key'));
    }

    protected function getSitemapUrl(): ?string
    {
        if (setting('sitemap_enabled', true)) {
            return route('public.sitemap');
        }

        return null;
    }
}
